#!/bin/bash
#$Revision:001$
#$Fri June 7:18 IST 2024$

#Variables
BASE=/home/ubuntu/shell-scripts  /* You can add Base address by your own*/
DAYS=10
DEPTH=1
RUN=0


#Check if the directory is present or not
if [ ! -d $BASE ]
then
        echo "directory does not exist: $BASE"
        exit 1
fi

#Create 'archieve' folder if not present
if [ ! -d $BASE/archive ]
then
        mkdir $BASE/archive
fi

#Find the list of files largest than 20MB
for i in 'find $BASE -maxdepth $DEPTH -type f -size +20M'
do
        if [ $RUN -eq 0 ]
        then
                echo "[$(date "+%Y-%m-%d %H:%M:%S")] archive $i ==> $BASE/archive"
                gzip $i || exit 1
                mv $i.gz $BASE/archive || exit 1
        fi
done
